version: '3.3'
services:
    db:
      image: mysql:8.0
      restart: always
      environment:
        MYSQL_DATABASE: 'banking'
        # So you don't have to use root, but you can if you like
        MYSQL_USER: 'banker'
        # You can use whatever password you like
        MYSQL_PASSWORD: 'password'
        # Password for root access
        MYSQL_ROOT_PASSWORD: 'password'
      expose:
          - '3306'  
      ports:
        # <Port exposed> : < MySQL Port running inside container>
        - '3306:3306'